### ISSUE TITLE
Java 17 !?

### ISSUE THREAD

**Issue by grebulon** [crow-misia/libmediasoup-android#37]
Wanted to use your library in an old project but couldn't since it is built with Java 17 and the old project is built with Java 11.
From reasons that I can't list here, it's not viable to move this old project to Java 17, so I was wandering if any of the great new upgrades to the Java language is really needed here?

**Comment by crow-misia** [comment]
@grebulon 
This library is Java 11 bytecode. but contains libwebrtc.jar, which is Java 17.

The libwebrtc.jar is generated when libwebrtc is built, and is not easy to change.

It can be used by using desugar and setting the Java17 code to be usable on older devices.
https://developer.android.com/build/jdks
https://developer.android.com/studio/write/java11-default-support-table

**Comment by grebulon** [comment]
Thanks for the response, but this won't work for me. I'm tied to an obsolete build system that I can't really control. Adding desugaring seems even more diffucult than upgrading to Java 17.

**Comment by grebulon** [comment]
Java 17 will have to do...
