### ISSUE TITLE
Demo not working with a toast [websocket disconnected]

### ISSUE THREAD

**Issue by rohg007** [crow-misia/libmediasoup-android#4]
Hey,

I tried running the demo app provided on the Readme.md. However, it doesn't work with a message WebSocket disconnected. It doesn't connect to the WebSocket even after 10 retries. Attaching logs. 
![Screenshot (140)](https://user-images.githubusercontent.com/32675945/126771523-c3e3709d-449e-4d8a-9e50-90b05af16894.png)

**Comment by crow-misia** [comment]
@rohg007 
The server for official demo seems to be down, as WebSocket errors are occurring even when accessing from web browser.

**Comment by rohg007** [comment]
Yup the official mediasoup servers seem to be down, but when I try to attach to an active third party wss server, it gives me the same issue. Do I need to change the url anywhere else apart from UrlFactory.kt?

**Comment by crow-misia** [comment]
@rohg007 
HOSTNAME and PORT settings in UrlFactory need to be set for that third party server.
I don't know which third party server you are using, but it may be a different port or the port is not open.

**Comment by rohg007** [comment]
@crow-misia Going deeper into the issue, the socket times out. Also, it doesn't reach the joinImpl() function at all. Attaching logs for that as well. 
![Screenshot (145)](https://user-images.githubusercontent.com/32675945/126866466-8afc089a-45c4-4801-b75c-01affe2e1828.png)
![Screenshot (146)](https://user-images.githubusercontent.com/32675945/126866471-bb49d699-d807-46a9-b5cd-83709987e74e.png)

I've checked the same wss URL on a web version and it works fine.

**Comment by crow-misia** [comment]
@rohg007 
This library is not associated with any network communication.
Also, mediasoup-demo-android is just a sample.

WebSocketTransport has a process to create an instance of OkHttpClient, so please adjust the timeout time there.

**Comment by rohg007** [comment]
Resolved. There was a problem with my web socket server. Closing the issue. Thanks!
