### ISSUE TITLE
 Is libmediasoupclient version 3.4.0 used in this code?

### ISSUE THREAD

**Issue by xujingzhou** [crow-misia/libmediasoup-android#4]
Hi, 

1. Is libmediasoupclient version 3.4.0 used in this code?

2. download failed as below cmd for libmediasoupclient
    https://github.com/versatica/libmediasoupclient/archive/55d724ff8b036991b0f0688adb334df976e458fe.tar.gz

**Comment by crow-misia** [comment]
1. Yes.
2. Check the network environment. That URL is working.

**Comment by xujingzhou** [comment]
thanks.I'll look into it
