### ISSUE TITLE
What should I do if I want to compile this project? For example, enter what cmd manually?

### ISSUE THREAD

**Issue by xujingzhou** [crow-misia/libmediasoup-android#5]
Hi, What should I do if I want to compile this project? For example, enter what cmd manually?

**Comment by crow-misia** [comment]
Written build instructions. ([Building.md](../blob/main/Building.md))

**Comment by xujingzhou** [comment]
Praise you for a great job!   I can compile it now, but why can't I find the generated .so file? How do I get a native compiled generated. so?

// ---------------------------------------------------
root@ubuntu:/home/webrtc/mediasoup/libmediasoup-android-m97# ./gradlew

> Configure project :core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
Checking the license for package NDK (Side by side) 24.0.8215888 in /home/android-sdk/licenses
License for package NDK (Side by side) 24.0.8215888 accepted.
Preparing "Install NDK (Side by side) 24.0.8215888 (revision: 24.0.8215888)".
"Install NDK (Side by side) 24.0.8215888 (revision: 24.0.8215888)" ready.
Installing NDK (Side by side) 24.0.8215888 in /home/android-sdk/ndk/24.0.8215888
"Install NDK (Side by side) 24.0.8215888 (revision: 24.0.8215888)" complete.
"Install NDK (Side by side) 24.0.8215888 (revision: 24.0.8215888)" finished.
Checking the license for package CMake 3.18.1 in /home/android-sdk/licenses
License for package CMake 3.18.1 accepted.
Preparing "Install CMake 3.18.1 (revision: 3.18.1)".
"Install CMake 3.18.1 (revision: 3.18.1)" ready.
Installing CMake 3.18.1 in /home/android-sdk/cmake/3.18.1
"Install CMake 3.18.1 (revision: 3.18.1)" complete.
"Install CMake 3.18.1 (revision: 3.18.1)" finished.
Creating maven publication
    Group: io.github.crow-misia.libmediasoup-android
    Artifact: libmediasoup-android
    Version: 0.10.0

> Task :help

Welcome to Gradle 7.4.2.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see more detail about a task, run gradlew help --task <task>

To see a list of command-line options, run gradlew --help

For more detail on using Gradle, see https://docs.gradle.org/7.4.2/userguide/command_line_interface.html

For troubleshooting, visit https://help.gradle.org

**Comment by crow-misia** [comment]
Please check carefully.
Looks like you are not understanding how to use gradle.
I'm not your support center.

**Comment by xujingzhou** [comment]
I'm sorry. It's my fault. It's all right now.  I wrote "./gradlew build" as "./gradlew".
