### ISSUE TITLE
No implementation found for boolean org.webrtc.LibvpxVp9Decoder.nativeIsSupported()

### ISSUE THREAD

**Issue by rohg007** [crow-misia/libmediasoup-android#5]
Hey @crow-misia, 
I was using libmediasoup in JAVA and I'm facing this specific error. It looks like one of my VP9 codecs isn't supported but I may be wrong. I am attaching the exact error and also attaching how I'm initializing the peerConnectionFactory in RoomClient. Feels like my peerConnectionFactory initialization is wrong somewhere.

![Screenshot (154)](https://user-images.githubusercontent.com/32675945/128248429-e0fa818b-5d11-4940-8083-f4dd875560a6.png)

![Screenshot (155)](https://user-images.githubusercontent.com/32675945/128248484-cbb8b07a-74f8-4362-a61c-b7eeb5ce0d8e.png)

If more info is required, let me know.

**Comment by crow-misia** [comment]
@rohg007 
Because native libraries have not been loaded.
Initialize library by calling the initialize method of MediasoupClient on Application class.

**Comment by rohg007** [comment]
Got it. I did initialize MediasoupClient in the Application class but didn't mention the application class in the manifest, that's why this issue.

**Comment by rohg007** [comment]
@crow-misia 
I ran into another issue, I'm getting JSON parse error while trying to join a room. So I checked and I have a valid JSON for router Rtp Capabilities and createSendTransport. But after fetching createSendTransport it throws a JSONParseError. 
![Screenshot (156)](https://user-images.githubusercontent.com/32675945/128289518-a60ca411-72fe-4d07-bde6-a445c1f84729.png)

**Comment by rohg007** [comment]
Precisely the error is occurring here

![Screenshot (158)](https://user-images.githubusercontent.com/32675945/128290136-0b7e4f23-b005-4016-bccd-6dc204d799bb.png)

**Comment by crow-misia** [comment]
@rohg007 
You are mistyping.
It's dtlsParameters, not dltsParameters.

I am not your support center.

**Comment by rohg007** [comment]
Thanks for the reply. I'm sorry for the trouble. Closing the issue.
