### ISSUE TITLE
Vulnerable WebRTC version.

### ISSUE THREAD

**Issue by mehrdadhadifar** [crow-misia/libmediasoup-android#6]
Hi,
It seems the version of WebRTC which is used use usrsctp, a third-party library that is the source of the vulnerabilities, and is no longer used by WebRTC. please update the version of webrtc.

**Comment by crow-misia** [comment]
welcome your pull requests!

**Comment by crow-misia** [comment]
@mehrdadhadifar 

libmediasoup-android using m102 is released.
https://github.com/crow-misia/libmediasoup-android/releases/tag/v0.11.0

https://search.maven.org/artifact/io.github.crow-misia.libmediasoup-android/libmediasoup-android
