### ISSUE TITLE
Echo + Voice loop back in Android

### ISSUE THREAD

**Issue by ahmedbhesaniya97** [crow-misia/libmediasoup-android#7]
Hello, @crow-misia
We have been using your library (latest version) for three to four months, and while it was previously flawless, we currently have two significant problems.
1. Noise and echoes are produced during the session.
2. When someone uses their phone to speak, they get their voice back.

**Comment by crow-misia** [comment]
very busy and can't find time.

**Comment by crow-misia** [comment]
Could not find the issue with Pixel6a and PC browser.

It may depend on hardware echo canceller in Android device, AudioManager settings, and other factors.

You may need to set WebRTC's MediaConstraints correctly, but you should explore this issue in your environment.

**Comment by ahmedbhesaniya97** [comment]
Hi @crow-misia 
Thanks for responding.
Did you try with two mobile devices ?

**Comment by ahmedbhesaniya97** [comment]
Previously, everything was functioning flawlessly, but a week ago, we noticed this problem happen in certain of our key devices.

**Comment by ahmedbhesaniya97** [comment]
We were able to address the Noise and Echo issues by passing a specific MediaConstraints attribute. But the voice loopback problem is not resolve (We are on it since week :cry:).

**Comment by crow-misia** [comment]
What MediaConstraints attribute did you set?

I installed mediasoup-demo-android app on Pixel6a and ZenFone3 and checked it, but cannot confirm the issue.

When two devices are placed side by side, the microphone picks up the sound of both devices. It is need to keep them in separate rooms or otherwise minimize the interference.

**Comment by ahmedbhesaniya97** [comment]
Hi @crow-misia 
We passed this attribute for resolving Echo issue.
```
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googEchoCancellation", "false"));
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googEchoCancellation2", "false"));
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googAutoGainControl", "false"));
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googAutoGainControl2", "false"));
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googNoiseSuppression", "false"));
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googNoiseSuppression2", "false"));
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googNoiseReduction", "false"));
audiomediaContraints.mandatory.add(new MediaConstraints.KeyValuePair("googHighpassFilter", "false"));
```

```
JavaAudioDeviceModule.builder(appContext)
        .setUseHardwareAcousticEchoCanceler(false)
        .setUseHardwareNoiseSuppressor(false)
        .setAudioRecordErrorCallback(audioRecordErrorCallback)
        .setAudioTrackErrorCallback(audioTrackErrorCallback)
        .createAudioDeviceModule();
```
As you can see, we also set `setUseHardwareAcousticEchoCanceler` and `setUseHardwareNoiseSuppressor` to false.

Above parameter helps us to resolve echo issue in our devices

**Comment by ahmedbhesaniya97** [comment]
**Voice Loop back Issue**

To eliminate interference, we tested on multiple networks with the device far away from other device.

We also test your mediaSoup demo, but voice is coming from Earpiece. so we set `isSpeakerphoneOn` and `communicationMode` .
```
val audioManager : AudioManager = context.getSystemService(Context.AUDIO_SERVICE) as AudioManager
audioManager.isSpeakerphoneOn = true
audioManager.mode = AudioManager.MODE_IN_COMMUNICATION
```

In demo, we got the loop back voice, let me attach video for the same.
I and my colleague are taking session and she is getting her voice in her device.

Device : Samsung M52(Android OS 12), Realme 5 Pro(Android OS 11)

https://user-images.githubusercontent.com/65531261/205428266-666f0010-f096-4e7b-9172-e71bca920e9e.mp4

**Comment by crow-misia** [comment]
I have checked it.

Seems to be caused by echo cancellation not working.

You need AudioSource set to VOICE_COMMUNICATION, not MIC, if you want to enable echo cancellation and noise reduction on the device.

Try the following settings.


```
JavaAudioDeviceModule.builder(appContext)
   ...
   .setUseHardwareAcousticEchoCanceler(true)
   .setUseHardwareNoiseSuppressor(true)
   .setAudioSource(android.media.MediaRecorder.AudioSource.VOICE_COMMUNICATION)
   ...
   .createAudioDeviceModule()
```

**Comment by ahmedbhesaniya97** [comment]
Thanks @crow-misia 
Let us try.

**Comment by ahmedbhesaniya97** [comment]
@crow-misia 
Did you face the same issue while setting `MIC` ?
